name: Check Licenses

on:
  workflow_call:  # 他のワークフローからの呼び出しを許可
  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  check-licenses:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-licenses
        if (Test-Path requirements.txt) { pip install -r requirements.txt }
        
    - name: Run license check
      run: |
        python scripts/check_licenses.py
        
    - name: Upload LICENSES.md as artifact
      uses: actions/upload-artifact@v4
      with:
        name: licenses-report
        path: LICENSES.md
        
    - name: Check for license changes
      shell: pwsh
      run: |
        git add LICENSES.md
        git diff --staged --quiet
        if ($LASTEXITCODE -eq 0) {
          Write-Output "ライセンス情報に変更はありません。"
        } else {
          Write-Output "::warning::ライセンス情報に変更があります。最新のライセンス情報はartifactからダウンロード可能です。"
          Write-Output "詳細な変更はartifactで確認してください"
        } 