name: Check Licenses

on:
  workflow_call:  # 他のワークフローからの呼び出しを許可
  push:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    branches: [ main ]
    paths:
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  check-licenses:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-licenses
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run license check
      run: |
        python scripts/check_licenses.py
        
    - name: Upload LICENSES.md as artifact
      uses: actions/upload-artifact@v4
      with:
        name: licenses-report
        path: LICENSES.md
        
    - name: Check for license changes
      run: |
        git add LICENSES.md
        if git diff --staged --quiet; then
          echo "ライセンス情報に変更はありません。"
        else
          echo "::warning::ライセンス情報に変更があります。最新のライセンス情報はartifactからダウンロード可能です。"
          echo "変更のあるライセンス:"
          git diff --staged LICENSES.md | grep -E "^\+.*\|.*\|" | grep -v "^\+\|" || echo "詳細な変更はartifactで確認してください"
        fi 