name: リリースタグ作成

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'リリースタグ名（例: v1.0.0）'
        required: true
        type: string
      prerelease:
        description: 'プレリリースとして作成'
        required: false
        type: boolean
        default: false

jobs:
  create-tag:
    runs-on: windows-latest
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: GitとPowerShellの設定
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: タグの存在確認
        id: check_tag
        run: |
          $tagExists = git tag -l "${{ github.event.inputs.tag_name }}"
          if ($tagExists) {
            echo "tag_exists=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "tag_exists=false" >> $env:GITHUB_OUTPUT
          }
      
      - name: タグが既に存在する場合のエラー
        if: steps.check_tag.outputs.tag_exists == 'true'
        run: |
          echo "::error::タグ '${{ github.event.inputs.tag_name }}' は既に存在します。別のタグ名を選択してください。"
          exit 1
      
      - name: タグの作成とプッシュ
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          # 注釈付きタグを作成
          git tag -a ${{ github.event.inputs.tag_name }} -m "Release ${{ github.event.inputs.tag_name }}"
          
          # タグをプッシュ
          git push origin ${{ github.event.inputs.tag_name }}
      
      - name: リリースワークフローのトリガーを待機中
        run: |
          echo "タグ '${{ github.event.inputs.tag_name }}' が正常に作成され、GitHubにプッシュされました。"
          echo "これにより、release-exe.ymlワークフローが自動的にトリガーされます。"
          echo "GitHubのActionsタブでリリースビルドの進行状況を確認できます。"