name: リリースタグ作成

# リポジトリへの書き込み権限を追加
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag_increment:
        description: 'バージョン増分タイプ'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: 'patch'
      custom_tag:
        description: '独自タグ名（空白の場合は自動生成されます）'
        required: false
        type: string
      prerelease:
        description: 'プレリリースとして作成'
        required: false
        type: boolean
        default: false
      prerelease_id:
        description: 'プレリリース識別子（beta/alpha/rc）'
        required: false
        type: string
        default: 'beta'

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリ管理者権限の確認
        id: check_permissions
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            try {
              // リポジトリに対する呼び出し元のユーザー権限を取得
              const { data: permissions } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner,
                repo,
                username: context.actor,
              });
              
              console.log(`ユーザー ${context.actor} の権限: ${permissions.permission}`);
              
              // admin権限を持つユーザーのみ実行可能
              if (permissions.permission === 'admin') {
                return 'authorized';
              } else {
                core.setFailed(`このワークフローを実行する権限がありません。リポジトリの管理者権限が必要です。`);
                return 'unauthorized';
              }
            } catch (error) {
              console.error(`エラー: ${error.message}`);
              core.setFailed(`権限の確認中にエラーが発生しました: ${error.message}`);
              return 'error';
            }
    outputs:
      status: ${{ steps.check_permissions.outputs.result }}

  create-tag:
    needs: check-permissions
    if: needs.check-permissions.outputs.status == 'authorized'
    runs-on: windows-latest
    
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          # トークン権限を使用するよう設定
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: GitとPowerShellの設定
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: 最新のタグとバージョン情報を取得
        id: get_version
        run: |
          # 最新のタグを取得
          $latestTag = git describe --tags --abbrev=0 2>$null || echo "v0.0.0"
          echo "latest_tag=$latestTag" >> $env:GITHUB_OUTPUT
          
          # v1.2.3 形式からバージョン部分を抽出
          if ($latestTag -match "v?(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?") {
            $major = [int]$Matches[1]
            $minor = [int]$Matches[2]
            $patch = [int]$Matches[3]
            
            # 増分タイプに応じてバージョンを更新
            switch ("${{ github.event.inputs.tag_increment }}") {
              "major" {
                $major++
                $minor = 0
                $patch = 0
              }
              "minor" {
                $minor++
                $patch = 0
              }
              "patch" {
                $patch++
              }
            }
            
            # 新しいバージョンタグを構築
            $newTag = "v${major}.${minor}.${patch}"
            if ("${{ github.event.inputs.prerelease }}" -eq "true") {
              $prelId = "${{ github.event.inputs.prerelease_id }}"
              if ([string]::IsNullOrEmpty($prelId)) {
                $prelId = "beta"
              }
              $newTag = "${newTag}-${prelId}"
            }
            echo "new_tag=$newTag" >> $env:GITHUB_OUTPUT
          } else {
            $newTag = "v0.1.0"
            if ("${{ github.event.inputs.prerelease }}" -eq "true") {
              $prelId = "${{ github.event.inputs.prerelease_id }}"
              if ([string]::IsNullOrEmpty($prelId)) {
                $prelId = "beta"
              }
              $newTag = "${newTag}-${prelId}"
            }
            echo "new_tag=$newTag" >> $env:GITHUB_OUTPUT
          }
      
      - name: タグ名を決定
        id: decide_tag
        run: |
          # カスタムタグが指定されていればそれを使用、そうでなければ自動生成したタグを使用
          $customTag = "${{ github.event.inputs.custom_tag }}"
          if ([string]::IsNullOrEmpty($customTag)) {
            $tagToUse = "${{ steps.get_version.outputs.new_tag }}"
          } else {
            # カスタムタグが v で始まらない場合は追加
            if (-not $customTag.StartsWith("v")) {
              $tagToUse = "v$customTag"
            } else {
              $tagToUse = "$customTag"
            }
            
            # プレリリースフラグが有効で、カスタムタグにプレリリース識別子がなければ追加
            if ("${{ github.event.inputs.prerelease }}" -eq "true" -and -not $tagToUse.Contains("-")) {
              $prelId = "${{ github.event.inputs.prerelease_id }}"
              if ([string]::IsNullOrEmpty($prelId)) {
                $prelId = "beta"
              }
              $tagToUse = "${tagToUse}-${prelId}"
            }
          }
          
          echo "使用するタグ: $tagToUse"
          echo "tag_to_use=$tagToUse" >> $env:GITHUB_OUTPUT
          
          # タグがプレリリースフォーマットかどうかをチェック
          $isPrerelease = $tagToUse -match "-"
          echo "is_prerelease=$isPrerelease" >> $env:GITHUB_OUTPUT
      
      - name: タグの存在確認
        id: check_tag
        run: |
          $tagToCheck = "${{ steps.decide_tag.outputs.tag_to_use }}"
          $tagExists = git tag -l "$tagToCheck"
          
          if ($tagExists) {
            echo "tag_exists=true" >> $env:GITHUB_OUTPUT
            echo "警告：タグ '$tagToCheck' は既に存在します"
          } else {
            echo "tag_exists=false" >> $env:GITHUB_OUTPUT
          }
      
      - name: タグが既に存在する場合のエラー
        if: steps.check_tag.outputs.tag_exists == 'true'
        run: |
          echo "::error::タグ '${{ steps.decide_tag.outputs.tag_to_use }}' は既に存在します。別のタグ名を選択してください。"
          exit 1
      
      - name: タグの作成とプッシュ
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          $tagToCreate = "${{ steps.decide_tag.outputs.tag_to_use }}"
          $isPrerelease = "${{ steps.decide_tag.outputs.is_prerelease }}" -eq "True"
          
          # タグのメッセージにプレリリース情報を含める
          $tagMessage = "Release $tagToCreate"
          if ($isPrerelease) {
            $tagMessage = "Prerelease $tagToCreate"
          }
          
          # 注釈付きタグを作成
          git tag -a $tagToCreate -m "$tagMessage"
          
          # タグをプッシュ
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $tagToCreate
          
          echo "タグ '$tagToCreate' を作成し、プッシュしました"
          if ($isPrerelease) {
            echo "このタグはプレリリースとして識別されます"
          }
      
      - name: 結果出力
        run: |
          echo "最新のタグ: ${{ steps.get_version.outputs.latest_tag }}"
          echo "作成したタグ: ${{ steps.decide_tag.outputs.tag_to_use }}"
          $isPrerelease = "${{ steps.decide_tag.outputs.is_prerelease }}" -eq "True"
          if ($isPrerelease) {
            echo "タイプ: プレリリース"
          } else {
            echo "タイプ: 正式リリース"
          }
          echo "これにより、release-exe.ymlワークフローが自動的にトリガーされます。"
          echo "GitHubのActionsタブでリリースビルドの進行状況を確認できます。"