name: Build and Release EXE

permissions:
  contents: write

on:
  # 他のワークフローからの呼び出しをサポート
  workflow_call:
    inputs:
      tag_name:
        description: 'ビルド対象のタグ名'
        required: true
        type: string
      is_prerelease:
        description: 'プレリリースかどうか'
        required: false
        type: string
        default: 'false'

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          # 指定されたタグを使用
          ref: ${{ inputs.tag_name }}

      - name: タグ情報の取得
        id: tag_info
        run: |
          # タグ名を取得
          $tag = "${{ inputs.tag_name }}"
          $isPrerelease = "${{ inputs.is_prerelease }}" -eq "true"
          
          echo "tag_name=$tag" >> $env:GITHUB_OUTPUT
          echo "is_prerelease=$isPrerelease" >> $env:GITHUB_OUTPUT
          
      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: 依存パッケージインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: EXEビルド
        run: |
          pyinstaller --noconfirm --onefile --windowed --name WindowCaptureReading --add-data "src;src" --add-data "resources;resources" src/gui_main.py --distpath dist

      - name: リリース作成とEXEファイルアップロード
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_info.outputs.tag_name }}
          name: Release ${{ steps.tag_info.outputs.tag_name }}
          draft: false
          prerelease: ${{ steps.tag_info.outputs.is_prerelease == 'True' }}
          files: dist/WindowCaptureReading.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 