name: Tests

on:
  workflow_call:  # 他のワークフローからの呼び出しを許可
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests
      run: |
        python -m pytest tests/ --cov=src/ --cov-report=xml

    - name: Add UTF-8 encoding to coverage.xml
      run: |
        (Get-Content coverage.xml) -replace '<\?xml version="1.0" \?>', '<?xml version="1.0" encoding="UTF-8"?>' | Set-Content coverage.xml -Encoding UTF8

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
      env:
        PYTHONIOENCODING: utf-8
        PYTHONUTF8: 1